### PR TITLE
Resubmitting Assignment01

### PR DESCRIPTION
**Pull request by lombardic**
Resubmitting assignment01 (mailroom.py) to add the missing sort feature from the first submission. Made minor changes to use the sum() function of list for calculating the total donations for each donor. Please look at mailroom.py for confirmation of added sort feature to complete Assignment01.

### CODE REVIEW

**Comment by natasha-aleksandrova** [comment]
your updates to lesson 3 look good - is your lesson 4 mailroom ready for review?

**Comment by natasha-aleksandrova** [comment]
haven't heard back and don't see submission on the website for lesson 4 - assuming not ready for review.

**Comment by lombardic** [comment]
Hi Natasha,

I apologize for the delayed response. I did not check my emails this weekend. You are correct to assume Mailroom Part 2 was not ready for review yet. I have a few more changes to make. I will complete those tonight and create another pull request indicating its completion. Sorry for the inconvenience. 

Thanks,
Chris Lombardi

**Comment by natasha-aleksandrova** [comment]
No worries! Thank you for following up.

**Pull request merged**
