### PR TITLE
Fixed trigrams.py, I think.

### PR DESCRIPTION
**Pull request by bapandaOK44**

### CODE REVIEW

**Review by charlesrobison — APPROVED** [review]
Better, but still not quite right.  Let me know if you want to continue working this or would like help or office hours set up.

With sherlock_small.txt I'm getting the following output:

"and with the dark incidents of the Study in Scarlet, I was seized with a keen desire to see Holmes again, and to know how he was employing his extraordinary powers. His rooms were brilliantly lit, and, even as I looked up, I saw his tall, spare figure pass twice in a dark silhouette against the blind."

Ready to merge

**Comment by bapandaOK44** [comment]
Yes! Office hours, please!!

I don’t know why, but this assignment is giving me trouble. 

I ran it a few times and got different output each time. 

-- Barb

**Comment by charlesrobison** [comment]
Hi there - just chatted with Natasha and she approves your code adjustments.  I'll go ahead and adjust the grade :). Please let me know if you need anything else.

**Comment by bapandaOK44** [comment]
Thanks. I had talked with her on teams last week and it helped.  I know there’s more text processing that could be done but I wanted to move on and finish mailroom 2. 

-- Barb

**Pull request merged**
