### PR TITLE
Committing mail_room_pt2_revised. Thank you!

### PR DESCRIPTION
**Pull request by CCSt130**
I've made changes per recommendations to fix function that was breaking when adding new donors, handle an error condition when user enters a new donor then 'cancels' by selecting 'N' when prompted to enter a donation, and stylistic fixes. Thank you for reviewing!

### CODE REVIEW

**Comment by CCSt130** [comment]
Hi Charles,

Thank you for your reply. Unfortunately, I am confused. I attempted to reproduce the bug and I couldn’t.  Do you recall how you reproduced it?

Report Before Adding a Donation to Each Donor:

Donor Name                         | Total Given      | Num Gifts | Average Gift
-----------------------------------------------------------------------------------
Bill and Melinda Gates Foundation    $ 177,011,006.00   7           $ 25,287,286.57
Walton Family Foundation             $ 149,737,042.00   9           $ 16,637,449.11
Stichting INGKA Foundation           $ 107,615,000.00   4           $ 26,903,750.00
Buffet Foundation                    $  91,573,000.00   5           $ 18,314,600.00
Bezos Family Foundation              $  38,492,000.00   2           $ 19,246,000.00

Report After Adding a Donation to Each Donor:

Donor Name                         | Total Given      | Num Gifts | Average Gift
-----------------------------------------------------------------------------------
Bill and Melinda Gates Foundation    $ 189,324,462.00   8           $ 23,665,557.75
Walton Family Foundation             $ 162,082,720.00  10           $ 16,208,272.00
Stichting INGKA Foundation           $ 115,152,537.00   5           $ 23,030,507.40
Buffet Foundation                    $  98,119,546.00   6           $ 16,353,257.67
Bezos Family Foundation              $  46,029,537.00   3           $ 15,343,179.00

Thank you,
Chuck

**Comment by charlesrobison** [comment]
Hi @CCSt130 - the bug is when adding new donors.  If I add Bill Smith, it's only saving a single donation, no matter how many new donations are added.

**Comment by CCSt130** [comment]
Oh, I see. Thanks for the pointer. Don’t want to bore you with details—but to explain...This is due to the way I’ve set up the data structure, because I am using dates as a subkey—I am using today’s date as the new subkey—I was trying to reduce complexity and user input. Since that doesn’t met the reqs I will try to restructure.

As an aside, it looks like I will not pass the class, as there is no way I can complete all assignments by my deadline of 8/21.

Thanks,
Chuck

Sent from my iPhone

On Aug 13, 2019, at 1:49 PM, Charles Robison <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @CCSt130<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCCSt130&data=02%7C01%7C%7C418341d319e94a97289c08d7202fc2d7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637013261805425516&sdata=xouehdr3XsrPS1t8R0lymQP9HDMx5KuN72%2BWRJzXyiI%3D&reserved=0> - the bug is when adding new donors. If I add Bill Smith, it's only saving a single donation, no matter how many new donations are added.

**Comment by natasha-aleksandrova** [comment]
@CCSt130 I would suggest to simplify code (which would also reduce bugs).


Typical data structure for lesson 04:
```
donors = {"Bob Smith": [100, 202, 333], "Mary Jones": [200, 300, 203]}
```

**Comment by CCSt130** [comment]
Thank you for the suggestion. I appreciate it.

-Chuck

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Pull request merged**
