### PR TITLE
READ ME

### PR DESCRIPTION
**Pull request by Jaidjen**

### CODE REVIEW

**Comment by Jaidjen** [comment]
READ ME

**Comment by natasha-aleksandrova** [comment]
@Jaidjen thank you looks much better!

however you need to remove the files you already added at the root of the repository, you can do so via: `git rm AssignGrid.py`

**Comment by Jaidjen** [comment]
Hello,

I tried to remove it but it gave me this error message:
$ git rm AssignGrid.py
fatal: pathspec 'AssignGrid.py' did not match any files

**Comment by Jaidjen** [comment]
Thank you!

I was able to follow the instructions and I think I set it up ok. 

However, I get hung up on creating a file because when I do 

$ cd students/jaidjen 

It says there is no file or directory.  But when I tried to do 

$ mkdir jaidjen 

It says there is already a directory. So I am confused.

Sorry, I seem to be a little git challenged :( 

How do I resolve this issue?

Thank you!

**Comment by natasha-aleksandrova** [comment]
You're doing just fine 🙂 

This looks like more command line navigation challenges than git.

Remember that you're dealing with file/directory paths and when you execute `cd` or `mkdir` you have to be aware of where you are in the path. Your cd command failed because I think you were already in `jaidjen` directory which is why when you tried to create it again, it failed.

**Comment by natasha-aleksandrova** [comment]
you can run `ls` to see what is in the path you're in or `pwd` to see your current path.

Your path should end with `SP_Online_PY210` meaning you're in the root of the repo path.

You already have a directory there so no need to create another, you can create a new lesson folder via: `mkdir students/Jaidjen/lesson2`

you should remove those extra files from there, for example: `git rm AssignGrid.py`  but do make sure you're at the root of the repo.


If you get hung up on removing those files, you can add as a collaborator to your repo and I can take care of that for you.

**Comment by Jaidjen** [comment]
This is what I see when I tried the steps you described

diana@Djai-Penguin MINGW64 ~/Desktop/SP_Online_PY210-master/students
(master)
$ git rm AssignGrid.py
fatal: pathspec 'AssignGrid.py' did not match any files
diana@Djai-Penguin MINGW64 ~/Desktop/SP_Online_PY210-master/students
(master)
$ pwd
/c/Users/diana/Desktop/SP_Online_PY210-master/students
diana@Djai-Penguin MINGW64 ~/Desktop/SP_Online_PY210-master/students
(master)
$ mkdir students/Jaidjen/lesson2
mkdir: cannot create directory ‘students/Jaidjen/lesson2’: No such file or
directory

How do I add as a collaborator? I am so sorry. I am trying but I seem to be
stuck in a spot.

Thank you!

**Comment by natasha-aleksandrova** [comment]
```
diana@Djai-Penguin MINGW64 ~/Desktop/SP_Online_PY210-master/students
(master)
$ git rm AssignGrid.py 
```
----> you cannot remove from here because you are in `students` directory but your file is below that.
so you can do `cd ..` to a directory below and then you can run `git rm`
```

diana@Djai-Penguin MINGW64 ~/Desktop/SP_Online_PY210-master/students
(master)
$ pwd
/c/Users/diana/Desktop/SP_Online_PY210-master/students
diana@Djai-Penguin MINGW64 ~/Desktop/SP_Online_PY210-master/students
(master)
```
like I mentioned before, your path should end in `SP_Online_PY210`
```
$ mkdir students/Jaidjen/lesson2
mkdir: cannot create directory ‘students/Jaidjen/lesson2’: No such file or
directory
```

**Comment by natasha-aleksandrova** [comment]
I would recommend getting comfortable with `cd` command which stands for change directory.

**Comment by natasha-aleksandrova** [comment]
to add me as collaborator, go to settings:
Screen Shot 2019-05-31 at 2 26 10 PM


my username is `natasha-aleksandrova`

**Comment by Jaidjen** [comment]
I added you. Thank you!

**Comment by Jaidjen** [comment]
I think I did it correctly?

diana@Djai-Penguin MINGW64
/c/users/diana/desktop/SP_Online_PY210-master/students (master)
$ cd C:/users/diana/desktop/SP_Online_PY210-master/SP_Online_Py210
diana@Djai-Penguin MINGW64
/c/users/diana/desktop/SP_Online_PY210-master/SP_Online_Py210 (master)
$ git rm AssignGrid.py
rm 'AssignGrid.py'

**Comment by natasha-aleksandrova** [comment]
yes! you got it - now remember that you will need to run  `git commit` and `git push` commands just like you did when you submitted the files.

I'm going to let you try this before doing it myself so that you get some practice. This is a good learning exercise 🙂 .

**Comment by Jaidjen** [comment]
Thank you!

**Comment by natasha-aleksandrova** [comment]
Just checking in - have you a had a chance to look at my notes and try again? I still see the files.

Are you available tonight? I can meet with you online on zoom to help you out live. Let us know please.

**Comment by Jaidjen** [comment]
I saw the notes and tried it out. I thought it was gone. 

What time are you available tonight? I have work until 5 pm Alaska time. 

Thank you,
Diana

**Comment by natasha-aleksandrova** [comment]
I have a slot available 7:00-7:30PM Pacific time which I believe is 6pm your time?

zoom link is on the course website under office hours.

**Comment by Jaidjen** [comment]
That works for me!
Thank you! 
I appreciate it :)

**Comment by Jaidjen** [comment]
Hello,

I followed the zoom link and it’s asking me for a meeting ID?

**Comment by natasha-aleksandrova** [comment]
you shouldn't need a meeting ID. did you follow this link:
https://washington.zoom.us/my/python210sp ? I am online waiting for you to join.

**Pull request merged**
