### PR TITLE
Adding lesson 02 code. Files included are ther grid printer, fizzbuzz…

### PR DESCRIPTION
**Pull request by roslynm**
…, and the fibonacci series

### CODE REVIEW

**Comment by natasha-aleksandrova** [comment]
@roslynm there is no code included here - please check Files Changed tab

reach out if you need some help with git

**Comment by roslynm** [comment]
Walp. Ok... I tried again, and it looked like 3 files were changed?
Hopefully that goes through... if not ...then yes... I might need some more
github help.
[image: image.png]
Thanks,
Roslyn

**Comment by natasha-aleksandrova** [comment]
https://github.com/roslynm/SP_Online_PY210/commit/2cdfedf59a2d709d2286f9f78ea0fac9f15f2144


your commit has no code - let's sync together on a zoom session.

**Comment by roslynm** [comment]
That would be great, thank you. Do you have any availability tonight or
Thursday?

**Comment by natasha-aleksandrova** [comment]
@roslynm can you please send us an email (instead of on github)? charles can schedule OH for you.

**Pull request closed without merging**
