### PR TITLE
Fixed multiple prints in create_report

### PR DESCRIPTION
**Pull request by bromleysj**
Fixed multiple prints in create_report; however, I'd like some direction on creating a wrapper for my get_user_input function (I've commented out the relevant code).

### CODE REVIEW

**Comment by natasha-aleksandrova** [comment]
@bromleysj your wrapper is an overkill for your use case - you can just wrap the input() call directly with try/except without the need for wrapper

**Comment by natasha-aleksandrova** [comment]
when I uncommented your wrapper function the only error I got was:
```
Traceback (most recent call last):
  File "student.py", line 1, in <module>
    @safe_input
NameError: name 'safe_input' is not defined
```

Which means it cannot find your safe_input function, this is because you are using before defining it. If you move the definition above its usage then it should work.

**Comment by bromleysj** [comment]
Natasha,

I have a question re:lesson06 unittest: the examples provided by
https://nedbatchelder.com/text/test0.html all have the Portfolio as its own
standalone class; how are we to change our mailroom code into a class that
it too can be instantiated even though we haven't covered this material
yet?

Thanks,

Scott

**Comment by bromleysj** [comment]
One more question: what is the final deadline for all work to be submitted?

I want to make sure I'm on track to have everything done.

Scott

**Comment by natasha-aleksandrova** [comment]
> One more question: what is the final deadline for all work to be submitted? I want to make sure I'm on track to have everything done. Scott


your due date is 3/18

**Comment by natasha-aleksandrova** [comment]
@bromleysj mailroom will be converted into a class in Lesson 09.


For now you will be unit testing just the individual functions, the tutorial in Lesson 06 should have some tips on what parts to unit test:
https://uwpce-pythoncert.github.io/PythonCertDevel/exercises/mailroom-part4.html#guidelines


Two common libraries to use for unit testing are `pytest` and `unittest`

`pytest` uses functions style to write tests (and more preferred in the community)
`unittest` is very similar to Java unittest and is a class style


I would suggest `pytest` for Lesson 06.

**Pull request merged**
