### PR TITLE
All remaining work

### PR DESCRIPTION
**Pull request by JohnSkull**
Hi, really sorry. Time got away from me, I was trying to do too much to the final project. Lesson 09 mailroom is not in very good shape, I really tried to do way too much. Hopefully these are in ok enough shape for me to pass. In any case I need to get them all submitted asap. My apologies for trying to commit this all at once, especially since lesson09 has so many error right now.

### CODE REVIEW

**Comment by natasha-aleksandrova** [comment]
@JohnSkull make sure that you submit all of the remaining assignments on the course website as well. I see a lot are missing submissions.

**Comment by JohnSkull** [comment]
Hi Natasha, 

I did submit all the work through the website as well. I believe my deadline has passed for course submissions. So I am not sure I would be able to submit anything else for consideration. I did think that I had completed all graded materials within this merge request. Is there a specific file that is missing?

**Comment by natasha-aleksandrova** [comment]
@JohnSkull 8 assignments show as not attempted on the course website.

Please login to the course website and submit PR link for each assignment that has no submission. We will not be able to enter a grade with those missing. Please do so at your earliest convenience.

**Comment by JohnSkull** [comment]
Hi Natasha, Thank you. I realize that I submitted everything together, in single zip for many of the modules. I added a link to the correct pull requests and have submitted all the assignments now. All my work should have been committed and have a submission on the website. Thank you.

**Comment by natasha-aleksandrova** [comment]
@JohnSkull there are still assignments missing submission. You can go to Progress tab to validate.

**Comment by JohnSkull** [comment]
@natasha-aleksandrova The progress tab seems to be reporting incorrectly. For instance, I have a submission for Exercise 3.1: Slicing Lab that is waiting to be graded, and I have a submission on Assignment 1: Mailroom, Part 1 that has received a grade of 15/15, yet both asgmt 03 and Exer 03 show 0% progress. If I go to the individual submission pages, all are complete or are waiting on grading. I did combine many exercises and assignments into common zips, but I did specify in the descriptions.

**Comment by natasha-aleksandrova** [comment]
Screen Shot 2021-02-23 at 4 21 51 PM
Screen Shot 2021-02-23 at 4 22 28 PM


progress tab should show you specific assignments that are missing submissions.

make sure you hit NEXT button to submit for each individual -- I have a screenshot for FizzBuzz exercise as an example, which is an exercise after Grid Printer.

**Comment by JohnSkull** [comment]
@natasha-aleksandrova Ok, sorry, I see now. Thank you. I hit submit for everything that was missing. I had already included all the files in other zips, so hopefully it is not too much trouble to grab them from a single zip in the other tabs. I included all the git links too so, hopefully they are all gradable now, and I don't think I am missing anything now.

**Pull request merged**
