### PR TITLE
adding mailroom.py version 2.0

### PR DESCRIPTION
**Pull request by Reem0330**

### CODE REVIEW

**Comment by Reem0330** [comment]
Thank you for reviewing my work, is it possible if you have the time to highlight what are the low performing parts that was the case of decreasing my grade, just to make sure to improve them in the next assignment.

Thank you
Reem

**Comment by natasha-aleksandrova** [comment]
@Reem0330 there were no issues here - but its possible the original version did? I can double check that for you. It usually helps when you indicate in your PR that you are re-submitting an assignment to get full points.

**Comment by natasha-aleksandrova** [comment]
yes the original grade was for https://github.com/UWPCE-PythonCert-ClassRepos/SP_Online_PY210/pull/501

I have updated lesson5 mailroom to full grade - thanks for reaching out!

**Comment by Reem0330** [comment]
Thank you so much!!.. that made my day .. much appreciate it.


Regards
Reem

**Pull request merged**
