### PR TITLE
Completed mailroom.py part 3.

### PR DESCRIPTION
**Pull request by mgummel25**
Creating Pull request to submit assignment 4. Sorry @natasha-aleksandrova!

### CODE REVIEW

**Comment by natasha-aleksandrova** [comment]
@mgummel25 did you see my comment from your previous PR?

your fork is out of sync. I Can help you but you need to add me as a collaborator. 

Please reach out to us so we can get this sorted.

**Comment by mgummel25** [comment]
I added you as a collaborator yesterday. When's a good time to get this
sorted out?

Thanks,
Matt

**Comment by mgummel25** [comment]
Alternatively, I can delete my fork and start with something fresh.

**Comment by natasha-aleksandrova** [comment]
@mgummel25 thanks for reaching out. I'm going to try to get this sorted right now and then we'll see if you need to recreate your fork.

Thanks!

**Comment by natasha-aleksandrova** [comment]
@mgummel25 can you paste your output of `git remote -v` please

**Comment by natasha-aleksandrova** [comment]
@mgummel25 I think you do need to re-create your fork. Save you new work and then recommit.

Please make sure you added the upstream (check via git remote -v command) and sync with master often with these directions:
https://help.github.com/en/articles/syncing-a-fork

**Pull request closed without merging**
