### PR TITLE
more tweeks to the mailroom_OO exercise

### PR DESCRIPTION
**Pull request by Freemabe**

### CODE REVIEW

**Comment by Freemabe** [comment]
> 👍 nice work

Thank you! Does this mean I am done with this class and should sign up for the next one? 

Cheers, and thanks for grading all of my stuff / all of the critiques on my code!

-Ben

**Comment by natasha-aleksandrova** [comment]
yes you are all done 🙂 

you should receive an email within the next few weeks on the instructions to sign up for the next course - good luck!

**Comment by Freemabe** [comment]
> yes you are all done 🙂
> 
> you should receive an email within the next few weeks on the instructions to sign up for the next course - good luck!

Thank you for all of the guidance!

**Comment by natasha-aleksandrova** [comment]
> > yes you are all done 🙂
> > you should receive an email within the next few weeks on the instructions to sign up for the next course - good luck!
> 
> Thank you for all of the guidance!

my pleasure!

**Pull request merged**
