### PR TITLE
added and updated programs to lesson04

### PR DESCRIPTION
**Pull request by Chieu1**
Lesson04
  - mailroom_part2.py ( revised)
 - file_exercise.py (new)
    (included text file "students.txt" and jpeg file "sceneryz.jpg"

### CODE REVIEW

**Comment by Chieu1** [comment]
Charles,

You have reviewed mailroom part 2 from lesson 4. is it pkay to submit it for grading. I have also submitted 
rhe “file ecercise” from lesson 4 in github. Have you had a chance to look at it ? Please let me know.

Thanks,

Chieu

**Comment by natasha-aleksandrova** [comment]
@charlesrobison can you please answer @Chieu1 questions?

**Comment by charlesrobison** [comment]
Hi @Chieu1 - please submit work for grading right after submitting via Github.  There's no need to wait.  If there is additional work that needs to be done or corrections need to be made, your grade can be adjusted after additional reviews of your code in Github.  Does that make sense?

**Comment by Chieu1** [comment]
Charles 

I’ll submit mailroom part 2 and file exercise now.

Thanks,

Chieu

**Comment by Chieu1** [comment]
Charles,

Can you help me with this ?

I was unable to find an empty area “Assignment Submission Area”  to submit two exercises mailroom part 2 and file exercise for grading.

I just found  only filled area “Assignment Submission Area” for exercise “Dictionaries, sets, and  files”  and it said complete and graded.

Thanks 

Chieu

**Comment by Chieu1** [comment]
Charles,

I don’t know if you have s chance to
Look at my previous email. 
I was unable to submit two exercises:
File exercise and mailroom part 2 from lesson 4 for grading in Github.
There is no 
There are no assignment Submission
Area for me to paste the link and upload files

Also, I need help on the few exercises. Cam you tell me what day and hours( Chicago time) you are availble so we can talk.

Thanks,

Chieu

**Comment by natasha-aleksandrova** [comment]
@Chieu1 you have already submitted on the course website previously for mailroom part 2 which is why you cannot submit again; 

Your submission for mailroom 2 had this:
https://github.com/Chieu1/SP_Online_PY210/blob/master/students/chieu_quach/lesson04/dict_lab.py



Which is not mailroom nor is it a Pull Request link. **Please** ensure you are submitting a Pull Request link, you simply copy the link in your browser _after_ you create your pull request. This pull request link is:
`https://github.com/UWPCE-PythonCert-ClassRepos/SP_Online_PY210/pull/107`


@charlesrobison can you please double check if current grade for mailroom part 2 is still correct or if it needs to be adjusted. Thanks.

**Comment by Chieu1** [comment]
Natasha,
Thanks for looking into this. Also, please look at the "file exercise" from lesson 4.
Chieu
    On ‎Sunday‎, ‎April‎ ‎28‎, ‎2019‎ ‎03‎:‎56‎:‎17‎ ‎PM‎ ‎CDT, Natasha <notifications@github.com> wrote:  
 
 
@Chieu1 you have already submitted on the course website previously for mailroom part 2 which is why you cannot submit again;

Your submission for mailroom 2 had this:
https://github.com/Chieu1/SP_Online_PY210/blob/master/students/chieu_quach/lesson04/dict_lab.py

Which is not mailroom nor is it a Pull Request link. Please ensure you are submitting a Pull Request link, you simply copy the link in your browser after you create your pull request. This pull request link is:
https://github.com/UWPCE-PythonCert-ClassRepos/SP_Online_PY210/pull/107

@charlesrobison can you please double check if current grade for mailroom part 2 is still correct or if it needs to be adjusted. Thanks.

**Comment by natasha-aleksandrova** [comment]
@Chieu1 file exercise is not a graded assignment.

**Comment by Chieu1** [comment]
Natasha,
Okay, how about exercise mailroom part 2 from lesson 4. Is it looked good?  Want me to make more changes before you grade it ? I have questions about some exercises and like to talk to you in Zoom. I have requested it with Charles but seems like he is busy this week. Please let me know the day and time(Chicago time) you are available this week so I can talk with you.
I will take some time from work to try to catch up with my homework. 
Thanks,
Chieu
    On ‎Monday‎, ‎April‎ ‎29‎, ‎2019‎ ‎02‎:‎26‎:‎51‎ ‎PM‎ ‎CDT, Natasha <notifications@github.com> wrote:  
 
 
@Chieu1 file exercise is not a graded assignment.

**Comment by charlesrobison** [comment]
@Chieu1 - mailroom part 2 from lesson 4 still needs adjustments.  User needs to be able to add new donors and donations as well as add donations to existing donors.  There are also a lot of PEP8 indentation issues that need to be corrected.  All indentations should be 4 spaces.  Let me know if you need help installing a linter.

**Comment by Chieu1** [comment]
Charles,
I have tested my resubmitted mailroom part 2 codes and it allows user to add new donor to an existing donation list. Pleaselook at my attachment. I
According to mailroom part 2 instructions, you create this menu option
Choose an action:

1 - Send a Thank You to a single donor.
2 - Create a Report.
3 - Send letters to all donors.
4 - QuitPlease let me know


    On ‎Thursday‎, ‎May‎ ‎2‎, ‎2019‎ ‎10‎:‎48‎:‎02‎ ‎AM‎ ‎CDT, Charles Robison <notifications@github.com> wrote:  
 
 
@Chieu1 - mailroom part 2 from lesson 4 still needs adjustments. User needs to be able to add new donors and donations as well as add donations to existing donors. There are also a lot of PEP8 indentation issues that need to be corrected. All indentations should be 4 spaces. Let me know if you need help installing a linter.

**Pull request merged**
