### PR TITLE
submiting Lesson09 assignment

### PR DESCRIPTION
**Pull request by Reem0330**

### CODE REVIEW

**Comment by natasha-aleksandrova** [comment]
@Reem0330 please review the files you are submitting.

Lesson is not updated, the "bad" docstrings and bad syntax error is still there.


Lesson 09 shows as a zip. 


If you would like to receive full grade for both please address above issues at your earliest convenience, thanks!

**Comment by Reem0330** [comment]
https://github.com/UWPCE-PythonCert-ClassRepos/SP_Online_PY210/pull/572/commits/87700f5b5e0e37d8dc895c96a19a562d02a0f9d4

here is a link to lesson09 version 2, I hope this will work

**Comment by natasha-aleksandrova** [comment]
@Reem0330 yes I see it now 🙂  thank you for taking care of it!

**Comment by Reem0330** [comment]
Just wondering when I can see my lesson 09 grade, I hope this will not be effected since my class ended
Also I want to let you know I really appreciate your help, Im inspired by you since Im at the beginning of my career as developer.. 
thank you again, so excited to start my next python class,


Reem

**Comment by natasha-aleksandrova** [comment]
@Reem0330 thanks for the great feedback! 

you grade was entered two days so you should be all set 🙂

**Pull request merged**
