### PR TITLE
Mailroom Part 4 (Lesson06 Assignment) with Unit Tests

### PR DESCRIPTION
**Pull request by mglezglez**
**Mailroom Part 4 with Unit Tests (Assignment from Lesson06)**

**_Results of running unit tests_**

```
mercedes@MYLAP MINGW64 /c/UW/PythonCertificationCourse1/SP_Online_PY210/SP_Online_PY210/students/mgglez/lesson06/mailroom (master)
$ pytest --cov-report term-missing --cov=mailroom tests/ -v
============================= test session starts =============================
platform win32 -- Python 3.8.3, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- c:\python38\python.exe
cachedir: .pytest_cache
rootdir: C:\UW\PythonCertificationCourse1\SP_Online_PY210\SP_Online_PY210\students\mgglez\lesson06\mailroom
plugins: cov-2.11.1
collecting ... collected 16 items

tests/test_mailroom.py::TestMailroom::test_create_donor_report PASSED    [  6%]
tests/test_mailroom.py::TestMailroom::test_generate_donor_records_empty PASSED [ 12%]
tests/test_mailroom.py::TestMailroom::test_generate_donor_records_successfully PASSED [ 18%]
tests/test_mailroom.py::TestMailroom::test_generate_email PASSED         [ 25%]
tests/test_mailroom.py::TestMailroom::test_read_data_from_file_no_file_found PASSED [ 31%]
tests/test_mailroom.py::TestMailroom::test_read_data_from_file_successfully PASSED [ 37%]
tests/test_mailroom.py::TestMailroom::test_say_goodbye PASSED            [ 43%]
tests/test_mailroom.py::TestMailroom::test_send_letter_to_all_donors PASSED [ 50%]
tests/test_mailroom.py::TestMailroom::test_send_letter_to_all_donors_empty_list PASSED [ 56%]
tests/test_mailroom.py::TestMailroom::test_send_thank_you_to_single_donor_choice_add_new PASSED [ 62%]
tests/test_mailroom.py::TestMailroom::test_send_thank_you_to_single_donor_choice_invalid PASSED [ 68%]
tests/test_mailroom.py::TestMailroom::test_send_thank_you_to_single_donor_choice_invalid_donation PASSED [ 75%]
tests/test_mailroom.py::TestMailroom::test_send_thank_you_to_single_donor_choice_list PASSED [ 81%]
tests/test_mailroom.py::TestMailroom::test_send_thank_you_to_single_donor_choice_update_donor PASSED [ 87%]
tests/test_mailroom.py::TestMailroom::test_send_thank_you_to_single_donor_choice_zero_donation PASSED [ 93%]
tests/test_mailroom.py::TestMailroom::test_write_data_to_file PASSED     [100%]

----------- coverage: platform win32, python 3.8.3-final-0 -----------
Name                     Stmts   Miss  Cover   Missing
------------------------------------------------------
__init__.py                  0      0   100%
mailroom.py                105     19    82%   18, 46-47, 182-201, 205
setup.py                     2      2     0%   1-3
tests\__init__.py            0      0   100%
tests\test_mailroom.py     116      1    99%   185
------------------------------------------------------
TOTAL                      223     22    90%


============================= 16 passed in 0.60s ==============================

```

### CODE REVIEW

**Review by charlesrobison — APPROVED** [review]
Works well!  Nice job on this. Make sure you submit this code to the course site for grading.

Ready to merge

**Review by mglezglez — COMMENTED** [review]
**Lesson07 Assignment (HTML Renderer) Unit Tests**

```
mercedes@MYLAP MINGW64 /c/UW/PythonCertificationCourse1/lesson07
$ pytest -vv
============================= test session starts =============================
platform win32 -- Python 3.8.3, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- c:\python38\python.exe
cachedir: .pytest_cache
rootdir: C:\UW\PythonCertificationCourse1\lesson07
plugins: cov-2.11.1
collecting ... collected 28 items

test_html_render.py::test_init PASSED                                    [  3%]
test_html_render.py::test_append PASSED                                  [  7%]
test_html_render.py::test_render_element PASSED                          [ 10%]
test_html_render.py::test_render_element2 PASSED                         [ 14%]
test_html_render.py::test_html PASSED                                    [ 17%]
test_html_render.py::test_body PASSED                                    [ 21%]
test_html_render.py::test_p PASSED                                       [ 25%]
test_html_render.py::test_sub_element PASSED                             [ 28%]
test_html_render.py::test_html_output2 PASSED                            [ 32%]
test_html_render.py::test_html_output3 PASSED                            [ 35%]
test_html_render.py::test_title PASSED                                   [ 39%]
test_html_render.py::test_one_line_tag_append PASSED                     [ 42%]
test_html_render.py::test_html_output4 PASSED                            [ 46%]
test_html_render.py::test_attributes PASSED                              [ 50%]
test_html_render.py::test_hr PASSED                                      [ 53%]
test_html_render.py::test_hr_attr PASSED                                 [ 57%]
test_html_render.py::test_br PASSED                                      [ 60%]
test_html_render.py::test_content_in_br PASSED                           [ 64%]
test_html_render.py::test_append_content_in_br PASSED                    [ 67%]
test_html_render.py::test_html_output5 PASSED                            [ 71%]
test_html_render.py::test_anchor PASSED                                  [ 75%]
test_html_render.py::test_html_output6 PASSED                            [ 78%]
test_html_render.py::test_html_output_7 PASSED                           [ 82%]
test_html_render.py::test_html_output8 PASSED                            [ 85%]
test_html_render.py::test_indent PASSED                                  [ 89%]
test_html_render.py::test_indent_contents PASSED                         [ 92%]
test_html_render.py::test_multiple_indent PASSED                         [ 96%]
test_html_render.py::test_element_indent1 PASSED                         [100%]

============================= 28 passed in 0.24s ==============================

```

**Lesson08 Assignment (The Circle Class) Unit Tests**

```
mercedes@MYLAP MINGW64 /c/UW/PythonCertificationCourse1/lesson08
$ pytest -vv
============================= test session starts =============================
platform win32 -- Python 3.8.3, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- c:\python38\python.exe
cachedir: .pytest_cache
rootdir: C:\UW\PythonCertificationCourse1\lesson08
plugins: cov-2.11.1
collecting ... collected 14 items

test_circle.py::TestCircle::test_circle_add PASSED                       [  7%]
test_circle.py::TestCircle::test_circle_comparison PASSED                [ 14%]
test_circle.py::TestCircle::test_circle_division PASSED                  [ 21%]
test_circle.py::TestCircle::test_circle_initialization_str_repr_and_properties PASSED [ 28%]
test_circle.py::TestCircle::test_circle_multiplication PASSED            [ 35%]
test_circle.py::TestCircle::test_circle_sort PASSED                      [ 42%]
test_circle.py::TestCircle::test_circle_subtraction PASSED               [ 50%]
test_sphere.py::TestSphere::test_circle_add PASSED                       [ 57%]
test_sphere.py::TestSphere::test_circle_comparison PASSED                [ 64%]
test_sphere.py::TestSphere::test_circle_division PASSED                  [ 71%]
test_sphere.py::TestSphere::test_circle_initialization_str_repr_and_properties PASSED [ 78%]
test_sphere.py::TestSphere::test_circle_multiplication PASSED            [ 85%]
test_sphere.py::TestSphere::test_circle_sort PASSED                      [ 92%]
test_sphere.py::TestSphere::test_circle_subtraction PASSED               [100%]

============================= 14 passed in 0.24s ==============================

```

**Review by charlesrobison — APPROVED** [review]
Html render and circle assignments reviewed and graded as well.  Great work!

Ready to merge

**Comment by mglezglez** [comment]
** Lesson09 Assignment - Mailroom Object Oriented with Unit Tests **

```
mercedes@MYLAP MINGW64 /c/UW/PythonCertificationCourse1/lesson09
$ pytest --cov-report term-missing --cov -vv
============================= test session starts =============================
platform win32 -- Python 3.8.3, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- c:\python38\python.exe
cachedir: .pytest_cache
rootdir: C:\UW\PythonCertificationCourse1\lesson09
plugins: cov-2.11.1
collecting ... collected 12 items

mailroom_oo/test_mailroom_oo.py::TestDonor::test_add_donation PASSED     [  8%]
mailroom_oo/test_mailroom_oo.py::TestDonor::test_generate_thank_you_email_to_single_donor PASSED [ 16%]
mailroom_oo/test_mailroom_oo.py::TestDonor::test_init PASSED             [ 25%]
mailroom_oo/test_mailroom_oo.py::TestDonorCollection::test_add_donor PASSED [ 33%]
mailroom_oo/test_mailroom_oo.py::TestDonorCollection::test_build_donor_collection_from_file PASSED [ 41%]
mailroom_oo/test_mailroom_oo.py::TestDonorCollection::test_generate_donor_report PASSED [ 50%]
mailroom_oo/test_mailroom_oo.py::TestDonorCollection::test_generate_letter_to_all_donors PASSED [ 58%]
mailroom_oo/test_mailroom_oo.py::TestDonorCollection::test_generate_letter_to_all_donors_list_empty PASSED [ 66%]
mailroom_oo/test_mailroom_oo.py::TestDonorCollection::test_get_donor_records PASSED [ 75%]
mailroom_oo/test_mailroom_oo.py::TestDonorCollection::test_init PASSED   [ 83%]
mailroom_oo/test_mailroom_oo.py::TestDonorCollection::test_load_donor_data_from_file PASSED [ 91%]
mailroom_oo/test_mailroom_oo.py::TestDonorCollection::test_save_donor_data_to_file PASSED [100%]

----------- coverage: platform win32, python 3.8.3-final-0 -----------
Name                              Stmts   Miss  Cover   Missing
---------------------------------------------------------------
mailroom_oo\donor_models.py         120      0   100%
mailroom_oo\test_mailroom_oo.py     138      5    96%   38, 66, 78, 90, 244
---------------------------------------------------------------
TOTAL                               258      5    98%


============================= 12 passed in 0.59s ==============================

```

**Comment by natasha-aleksandrova** [comment]
very nice test coverage!

**Review by natasha-aleksandrova — APPROVED** [review]

**Pull request merged**
