### PR TITLE
Lesson 7 - HTML Renderer Exercise

### PR DESCRIPTION
**Pull request by kylenod**
Hello,

Submitting my code for Lesson 7.

Best,
Kyle

### CODE REVIEW

**Review by charlesrobison — APPROVED** [review]
Unable to review - getting error: "AttributeError: module 'html_render' has no attribute 'Html'". Is this ready for review or do you need help?  Let me know if you have questions.

Ready to merge

**Comment by kylenod** [comment]
Hi Charles, I thought it was ready, but I must have missed something significant. Are you getting the attribute error when you run test_html_render, or is it from something else? Trying to figure out where to start with troubleshooting since the run_html_render and test_html_render are running as expected on my computer (I think).

Thanks,
Kyle

**Comment by charlesrobison** [comment]
Hi Kyle - I'll take another look tomorrow. Maybe I missed something.

**Comment by charlesrobison** [comment]
Hi Kyle - just re-checked and everything runs fine.  Error on my end - sorry about that!  I'll adjust the grade.

**Comment by kylenod** [comment]
Thanks Charles! Hope you have a happy New Years.

Best,

Kyle O’Donnell
(617) 784-9980 | kylenodonnell@gmail.com
http://linkedin.com/in/kyle-odonnell

**Pull request merged**
