### PR TITLE
Submit lesson05, lesson06 and lesson07

### PR DESCRIPTION
**Pull request by InduKolli**
Submit lesson05, lesson06 and lesson07

### CODE REVIEW

**Comment by natasha-aleksandrova** [comment]
@InduKolli your pr shows 127 changed files and git conflicts.

have you synced your fork recently?


please reach out to us if you have further questions.

**Comment by InduKolli** [comment]
Hi Natasha,

yes I did. Did I do wrong?
Not sure where that files came from.
Please let me know if I need to do any further corrections for the homework.

Thank you

Indu
________________________________

**Comment by InduKolli** [comment]
Hi Natasha,

Do I need to resubmit my homework?

Please let me know!

Thank you

Indu

________________________________

**Comment by natasha-aleksandrova** [comment]
your fork needs to be fixed first before you open a new PR.

can you tell what commands you ran to sync your fork?

**Comment by InduKolli** [comment]
Hi Natasha,

Here is what I typed after committing my homework:

$git pull upstream master

Thank you

Indu
________________________________

**Comment by natasha-aleksandrova** [comment]
please follow the steps in here:
https://help.github.com/en/articles/syncing-a-fork

let me know how it goes!

**Comment by InduKolli** [comment]
Hi Natasha,

i followed the instructions. And here is what I got:

[cid:513eaaa8-a2dd-494a-87bc-1a93129c3f3f]

Thank you

Indu



________________________________

**Comment by natasha-aleksandrova** [comment]
is there an attachment? I can't see it since it looks like you are replying from  your email.

If you comment on github directly then you can attach a screenshot.

**Comment by InduKolli** [comment]
GitHub

**Comment by natasha-aleksandrova** [comment]
looks like your git state is messed up.

If you add me as a contributor to your account via settings then I can try fixing this for you.

**Comment by InduKolli** [comment]
Hi Natasha,

How do I add you as a contributor to my account?
Please let me know.

Thank you very much for your support!

Indu
________________________________

**Comment by natasha-aleksandrova** [comment]
It's a setting under your repository (your fork).

Settings > Collaborators then add me. My username is natasha-aleksandrova

**Comment by InduKolli** [comment]
Hi Natasha,
I added you under collaborators.
Please let me know if you need any further information.

Thank you very much for all your support!

**Pull request closed without merging**
