### PR TITLE
added lesson06 folder

### PR DESCRIPTION
**Pull request by LongSA**
Contains all files necessary for lesson 6 exercises.

### CODE REVIEW

**Review by charlesrobison — APPROVED** [review]
Excellent work here.  Code works great - very thorough.  Great tests that pass.

Ready to merge

**Comment by LongSA** [comment]
Something seems to be broken in GitHub again. I opened my terminal window in my local class repository and did a git status and git pull upstream master, but the git pull is showing that there is something broken in the remote repository because the response to 2nd git status but it still thinks I'm merging. Here is what I see:

steve@Steves-MacBook-Pro SP_Online_PY210 % git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
steve@Steves-MacBook-Pro SP_Online_PY210 % 
steve@Steves-MacBook-Pro SP_Online_PY210 % 
steve@Steves-MacBook-Pro SP_Online_PY210 % 
steve@Steves-MacBook-Pro SP_Online_PY210 % git pull upstream master
remote: Enumerating objects: 94, done.
remote: Counting objects: 100% (94/94), done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 94 (delta 63), reused 79 (delta 54), pack-reused 0
Unpacking objects: 100% (94/94), done.
From https://github.com/UWPCE-PythonCert-ClassRepos/SP_Online_PY210
 * branch              master     -> FETCH_HEAD
   a8e5da3a..03391caa  master     -> upstream/master
hint: Waiting for your editor to close the file... bbedit -w: bbedit: command not found
error: There was a problem with the editor 'bbedit -w'.
Not committing merge; use 'git commit' to complete the merge.
steve@Steves-MacBook-Pro SP_Online_PY210 % git pull upstream master
error: You have not concluded your merge (MERGE_HEAD exists).
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge.
steve@Steves-MacBook-Pro SP_Online_PY210 % git status
On branch master
Your branch is up to date with 'origin/master'.

All conflicts fixed but you are still merging.
  (use "git commit" to conclude merge)

Changes to be committed:
	modified:   students/Ajay_Randhawa/lesson07/html_render.py
	modified:   students/Ajay_Randhawa/lesson07/run_html_render.py
	modified:   students/Ajay_Randhawa/lesson07/test_html_render.py
	new file:   students/barb_matthews/lesson5/except_exercise.py
	new file:   students/brent_kieszling/Lesson_05/Assignment_01/except_exercise.py
	new file:   students/brent_kieszling/Lesson_05/Assignment_01/except_test.py
	new file:   students/brent_kieszling/Lesson_05/Assignment_02/donor_history.dat
	new file:   students/brent_kieszling/Lesson_05/Assignment_02/mailroom_part_03.py
	new file:   students/cbrown/Lesson 5/mailroom_part3.py
	modified:   students/emorychristenson/lesson05/mailroom_pt3.py

steve@Steves-MacBook-Pro SP_Online_PY210 % git status
On branch master
Your branch is up to date with 'origin/master'.

All conflicts fixed but you are still merging.
  (use "git commit" to conclude merge)

Changes to be committed:
	modified:   students/Ajay_Randhawa/lesson07/html_render.py
	modified:   students/Ajay_Randhawa/lesson07/run_html_render.py
	modified:   students/Ajay_Randhawa/lesson07/test_html_render.py
	new file:   students/barb_matthews/lesson5/except_exercise.py
	new file:   students/brent_kieszling/Lesson_05/Assignment_01/except_exercise.py
	new file:   students/brent_kieszling/Lesson_05/Assignment_01/except_test.py
	new file:   students/brent_kieszling/Lesson_05/Assignment_02/donor_history.dat
	new file:   students/brent_kieszling/Lesson_05/Assignment_02/mailroom_part_03.py
	new file:   students/cbrown/Lesson 5/mailroom_part3.py
	modified:   students/emorychristenson/lesson05/mailroom_pt3.py

What should I do? The listed files are NOT mine. The application BBEdit has nothing to do with GitHub and there were no new files authored with BBEdit in my local repository yet. 

Was someone else in the middle of doing something that fouled up my request and does GitHub not allow multiple users to make requests at the same time? I'm at a standstill and don't have a lot of free time to work this problem. 

I will have to abandon using GitHub and email you the assignments if GitHub cannot be fixed or continues to break. I will continue doing the last couple of assignments. If it takes too long to fix GitHub I will have to check them in almost simultaneously to meet the time deadline.

Steve Long

**Comment by natasha-aleksandrova** [comment]
If bbedit is set as default github editor then that's why github would be tied to it.

No other student's work can really affect your fork and no other students we have are having these issues which seems like it is isolated to your github workflow.

You can email us your work if you'd like.

**Comment by LongSA** [comment]
Thanks, Natasha. I will email my work and work the interface problem in parallel and as time allows. This has only happened twice, so I’m looking for causative factors. I did not find a bug report on the BareBones site.

Steve

**Comment by LongSA** [comment]
One other thing: There was no point during the Git installation where I was directed to tell it what the default editor is, so this makes the bug especially puzzling, especially since it doesn’t happen all the time. If it is an interface issue with BBEdit, then it should happen every time. I’m thinking this is a bug on the client side Git tool. That doesn’t really help me, but will probably help the Git developer team when I log the issue.

Steve

**Comment by LongSA** [comment]
I’m still seeing this nonsense when I run git…

Last login: Thu Dec 17 13:36:27 on console
steve@Steves-MacBook-Pro SP_Online_PY210 % git status
On branch master
Your branch is up to date with 'origin/master'.

All conflicts fixed but you are still merging.
  (use "git commit" to conclude merge)

Changes to be committed:
	modified:   students/Ajay_Randhawa/lesson07/html_render.py
	modified:   students/Ajay_Randhawa/lesson07/run_html_render.py
	modified:   students/Ajay_Randhawa/lesson07/test_html_render.py
	new file:   students/barb_matthews/lesson5/except_exercise.py
	new file:   students/brent_kieszling/Lesson_05/Assignment_01/except_exercise.py
	new file:   students/brent_kieszling/Lesson_05/Assignment_01/except_test.py
	new file:   students/brent_kieszling/Lesson_05/Assignment_02/donor_history.dat
	new file:   students/brent_kieszling/Lesson_05/Assignment_02/mailroom_part_03.py
	new file:   students/cbrown/Lesson 5/mailroom_part3.py
	modified:   students/emorychristenson/lesson05/mailroom_pt3.py

steve@Steves-MacBook-Pro SP_Online_PY210 % pwd
/Users/steve/Documents/Project/python/uw_class/src/SP_Online_PY210
steve@Steves-MacBook-Pro SP_Online_PY210 % ls
README.md	examples	solutions	students
steve@Steves-MacBook-Pro SP_Online_PY210 % git --version
git version 2.24.1 (Apple Git-126)
steve@Steves-MacBook-Pro SP_Online_PY210 % git pull upstream master
error: You have not concluded your merge (MERGE_HEAD exists).
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge.
steve@Steves-MacBook-Pro SP_Online_PY210 % 

As you can see, none of the pending changes belong to me and this is what is holding me up. I’ve used git quite a bit over the last few years at work and we never had issues like this. I passed this incident on to some developers who are more knowledgeable than I am on this subject and they agreed that if I’m running git pull upstream master before doing an add/commit/push that this would not be happening unless the system is out of sync on the server. It has worked 6 times in a row without a problem for me. So, the consensus is that it’s not me; it’s the UW git project.

I have me my contractual obligations for the class in completing the assignment. I will take you up on your email offer for the remainder of the assignments. I will send the zipped files both thru the class web page AND as an attachment in email since I don’t know what you need to work with the goofy UW system.

Steve

**Comment by LongSA** [comment]
With GitHub down, I will be submitting assignments to email address python1@uw.edu  unless you wish me to use a different address.

Steve

**Pull request merged**
