### PR TITLE
Pull Request For Lesson05

### PR DESCRIPTION
**Pull request by IanMayther**
After resetting my repo, this is the pull request for Lesson05.  I will be starting Lesson06

### CODE REVIEW

**Comment by natasha-aleksandrova** [comment]
@IanMayther I'm a little confused - I don't see lesson05 submission in here?

**Comment by IanMayther** [comment]
My Lesson 05 is in my student folder.  Looking back I probably should have renamed my except exercises.  However, I modified the files that downloaded out of the Python Cert. assignment online.

**Comment by natasha-aleksandrova** [comment]
@IanMayther I'm sorry I'm not following - please check Files Changed tab; I don't see any except exercises in there.



I see what looks like beginning of Lesson 06?

**Comment by IanMayther** [comment]
@natasha-aleksandrova  I don't know what I did.  When you fixed the pull request it had my Lesson05 work in it.  The goal of this pull request was to create a PR for submitting lesson05 work.  However, it was already there.  Is there a way I can cancel this request?

Also, how would I update my pull request for the Lesson05 work that I have submitted so that Charles can grade it?

**Comment by natasha-aleksandrova** [comment]
I closed this PR.

you can pick a PR from all of your PRs:
https://github.com/UWPCE-PythonCert-ClassRepos/SP_Online_PY210/pulls?q=is%3Apr+author%3AIanMayther

and use that link for the submission on the course website.

**Pull request closed without merging**
