### PR TITLE
Upload of trigrams.py assignment

### PR DESCRIPTION
**Pull request by RandiPet**

### CODE REVIEW

**Comment by natasha-aleksandrova** [comment]
needs review - should not have been merged.

**Comment by natasha-aleksandrova** [comment]
@RandiPet everything looks great!

**Comment by RandiPet** [comment]
@natasha-aleksandrova Is there anything I need to fix  on the trigrams assignment? I noticed the grade is still 0 in the "Progress" tab on Start Learning. Wanted to make sure it's all good before continuing with the next lessons.

**Comment by pythonsavvy** [comment]
I'll check for you. Sorry for delay UW help desk have messed up my access and I can't get into the system to input grades. I'll check as soon as I get to my pc later today

**Comment by natasha-aleksandrova** [comment]
@RandiPet updated the grade for you, thanks for letting us know!

**Comment by natasha-aleksandrova** [comment]
@pythonsavvy I think you're in the wrong repo again :)

**Pull request merged**
