### PR TITLE
Create lesson04

### PR DESCRIPTION
**Pull request by Chieu1**

### CODE REVIEW

**Comment by charlesrobison** [comment]
@Chieu1 - this PR was created from a branch, patch-7, instead of master.  As we discussed in office hours, you don't want to use branching for this course, just submit everything from master.  I'm going to close this PR.  Anything you push from master will be added to your open PR.  That isn't a problem.  Let me know if you have questions.

**Comment by Chieu1** [comment]
Charles 

I have made the changes on mailroom part 2 and submitted to Github for you to review. 
Also, I have submitted the exercise 
“File Exercise” from lesson 4 with 
text file “students.txt” and 
jpeg file “sceneryz.jpg” 
Please let me know.

Thanks,

Chieu

**Comment by Chieu1** [comment]
Charles,

If you have the URL link to download Linter to use on the text editor, can 
ypu send it to me. I was unable to find it. I use editor python IDE version
3.7.2

Thanks,

Chieu

**Comment by natasha-aleksandrova** [comment]
@Chieu1 there are several online linters you can use:
http://pep8online.com/

you can install command line:
https://pypi.org/project/pep8/

you can also configure within your IDE (depending on which IDE you use)

You would need to do research to see what works for your environment/configuration, this is why I always recommend using Pycharm, it's best option with everything built-in that will work on any platform.

**Comment by Chieu1** [comment]
Natasha,

Thanks 

 Chieu

**Comment by Chieu1** [comment]
Hi Natasha/Charles,
I like to request for two weeks extension to complete the course. I am behind on my homework and need extend time towork on the remaining lessons in course. Please let me know
Thanks,
Chieu
    On ‎Tuesday‎, ‎April‎ ‎23‎, ‎2019‎ ‎02‎:‎55‎:‎07‎ ‎AM‎ ‎CDT, Chieu Q <chieu.quach@yahoo.com> wrote:  
 
 Natasha,
Thanks 
 Chieu

Sent from my iPhone
On Apr 23, 2019, at 1:25 AM, Natasha <notifications@github.com> wrote:



@Chieu1 there are several online linters you can use:
http://pep8online.com/

you can install command line:
https://pypi.org/project/pep8/

you can also configure within your IDE (depending on which IDE you use)

You would need to do research to see what works for your environment/configuration, this is why I always recommend using Pycharm, it's best option with everything built-in that will work on any platform.

**Comment by Chieu1** [comment]
Hi Chieu,

Your current end date is June 7th.  A two week extension will now make your end date June 21.  I hope this helps.  Please let me know if there's anything else I can do to assist.

Best,


Charles
________________________________

**Comment by Chieu1** [comment]
Charles,

Thanks for your help. I will try really hard to complete and pass the course. Appreciated.

Chieu

**Comment by Chieu1** [comment]
Hi Charles,

I have uodated  two programs: Mailroom 2 from lesson 4 and exercise exceptions from lesson 5.
I did pull request and they are ready
for you to take a look.

Thanks,

Chieu

**Pull request closed without merging**
